language: r
r:
  - release
  - devel
sudo: false
cache: packages

warnings_are_errors: true

addons:
  apt:
     update: true
     sources:
      - sourceline: 'ppa:opencpu/imagemagick'
     packages:
      - libmagick++-dev

before_install:
 - cd ndtv
 

notifications:
  email:
    on_success: never
    on_failure: change
